import { NextRequest, NextResponse } from "next/server";
import { getProject } from "@/lib/db";
import jsPDF from "jspdf";

/**
 * POST /api/export/pdf
 *
 * Exports a comic project as PDF
 */
export async function POST(request: NextRequest) {
  try {
    const body = await request.json();

    if (!body.sessionId) {
      return NextResponse.json(
        { success: false, error: "sessionId (projectId) is required." },
        { status: 400 }
      );
    }

    // Fetch project from database
    const project = await getProject(body.sessionId);
    
    if (!project) {
      return NextResponse.json(
        { success: false, error: "Project not found." },
        { status: 404 }
      );
    }

    // Check if project has approved pages
    const approvedPages = project.pages.filter(p => p.status === "approved");
    
    if (approvedPages.length === 0) {
      return NextResponse.json(
        { success: false, error: "No approved pages to export. Generate and approve pages first." },
        { status: 400 }
      );
    }

    const title = body.options?.title || project.title;
    const includeCover = body.options?.includeCover !== false;
    
    // Create PDF document
    const pdf = new jsPDF({
      orientation: "portrait",
      unit: "mm",
      format: "a4",
    });

    const pageWidth = pdf.internal.pageSize.getWidth();
    const pageHeight = pdf.internal.pageSize.getHeight();
    const margin = 20;
    const contentWidth = pageWidth - (margin * 2);

    let yPosition = margin;

    // Helper function to add text with wrapping
    const addWrappedText = (text: string, x: number, y: number, maxWidth: number, fontSize: number, fontStyle: "normal" | "bold" = "normal") => {
      pdf.setFontSize(fontSize);
      pdf.setFont("helvetica", fontStyle);
      const lines = pdf.splitTextToSize(text, maxWidth);
      pdf.text(lines, x, y);
      return y + (lines.length * fontSize * 0.4);
    };

    // Helper to check if we need a new page
    const checkNewPage = (neededHeight: number) => {
      if (yPosition + neededHeight > pageHeight - margin) {
        pdf.addPage();
        yPosition = margin;
        return true;
      }
      return false;
    };

    // Cover Page
    if (includeCover) {
      // Title
      pdf.setFontSize(36);
      pdf.setFont("helvetica", "bold");
      const titleLines = pdf.splitTextToSize(title, contentWidth);
      const titleHeight = titleLines.length * 15;
      pdf.text(titleLines, pageWidth / 2, pageHeight / 3, { align: "center" });
      
      // Genre and tone
      pdf.setFontSize(14);
      pdf.setFont("helvetica", "normal");
      pdf.text(`${project.genre} | ${project.tone}`, pageWidth / 2, pageHeight / 3 + titleHeight + 20, { align: "center" });
      
      // Synopsis
      if (project.synopsis) {
        pdf.setFontSize(10);
        const synopsisLines = pdf.splitTextToSize(project.synopsis, contentWidth * 0.8);
        pdf.text(synopsisLines, pageWidth / 2, pageHeight / 2 + 20, { align: "center" });
      }
      
      // Page count
      pdf.setFontSize(12);
      pdf.text(`${approvedPages.length} Pages`, pageWidth / 2, pageHeight - 40, { align: "center" });
      pdf.text("Generated by Comicore AI", pageWidth / 2, pageHeight - 30, { align: "center" });
      
      // Add new page for content
      pdf.addPage();
    }

    // Table of Contents
    yPosition = margin;
    pdf.setFontSize(20);
    pdf.setFont("helvetica", "bold");
    pdf.text("Table of Contents", margin, yPosition);
    yPosition += 15;

    approvedPages.forEach((page, index) => {
      pdf.setFontSize(12);
      pdf.setFont("helvetica", "normal");
      const pageNum = index + 1;
      pdf.text(`${pageNum}. ${page.title}`, margin, yPosition);
      pdf.text(`${pageNum}`, pageWidth - margin - 10, yPosition);
      yPosition += 8;
    });

    // Story Overview
    pdf.addPage();
    yPosition = margin;
    pdf.setFontSize(20);
    pdf.setFont("helvetica", "bold");
    pdf.text("Story Overview", margin, yPosition);
    yPosition += 12;
    
    if (project.roughOverview) {
      yPosition = addWrappedText(project.roughOverview, margin, yPosition, contentWidth, 10);
    }

    // Characters
    yPosition += 15;
    pdf.setFontSize(16);
    pdf.setFont("helvetica", "bold");
    pdf.text("Characters", margin, yPosition);
    yPosition += 10;

    project.characters.forEach((char) => {
      checkNewPage(20);
      pdf.setFontSize(12);
      pdf.setFont("helvetica", "bold");
      pdf.text(`${char.name} (${char.role})`, margin, yPosition);
      yPosition += 6;
      
      pdf.setFont("helvetica", "normal");
      pdf.setFontSize(10);
      if (char.description) {
        yPosition = addWrappedText(char.description, margin, yPosition, contentWidth, 10);
      }
      yPosition += 5;
    });

    // World Setting
    yPosition += 10;
    checkNewPage(30);
    pdf.setFontSize(16);
    pdf.setFont("helvetica", "bold");
    pdf.text("World Setting", margin, yPosition);
    yPosition += 10;

    if (project.world.setting) {
      yPosition = addWrappedText(`Setting: ${project.world.setting}`, margin, yPosition, contentWidth, 10);
    }
    if (project.world.atmosphere) {
      yPosition = addWrappedText(`Atmosphere: ${project.world.atmosphere}`, margin, yPosition, contentWidth, 10);
    }

    // Comic Pages
    approvedPages.forEach((page, index) => {
      pdf.addPage();
      yPosition = margin;

      // Page header
      pdf.setFontSize(16);
      pdf.setFont("helvetica", "bold");
      pdf.text(`Page ${index + 1}: ${page.title}`, margin, yPosition);
      yPosition += 3;

      // Page separator line
      pdf.setDrawColor(200, 200, 200);
      pdf.line(margin, yPosition, pageWidth - margin, yPosition);
      yPosition += 10;

      // Page script summary
      if (page.script) {
        pdf.setFontSize(11);
        pdf.setFont("helvetica", "italic");
        const scriptLines = pdf.splitTextToSize(page.script, contentWidth);
        pdf.text(scriptLines, margin, yPosition);
        yPosition += scriptLines.length * 5 + 10;
      }

      // Panels
      if (page.panels && page.panels.length > 0) {
        page.panels.forEach((panel, panelIndex) => {
          checkNewPage(40);

          // Panel header
          pdf.setFontSize(12);
          pdf.setFont("helvetica", "bold");
          const panelTitle = `Panel ${panel.panelNumber || panelIndex + 1}`;
          const moodText = panel.mood ? ` [${panel.mood}]` : "";
          const angleText = panel.cameraAngle ? ` [${panel.cameraAngle}]` : "";
          pdf.text(panelTitle + moodText + angleText, margin, yPosition);
          yPosition += 6;

          // Panel description
          if (panel.description) {
            pdf.setFontSize(10);
            pdf.setFont("helvetica", "normal");
            const descLines = pdf.splitTextToSize(panel.description, contentWidth);
            pdf.text(descLines, margin, yPosition);
            yPosition += descLines.length * 4 + 5;
          }

          // Dialogue
          if (panel.dialogue && panel.dialogue.length > 0) {
            panel.dialogue.forEach((d) => {
              checkNewPage(15);
              
              pdf.setFontSize(10);
              const typeLabel = d.type === "thought" ? "(thought)" : 
                               d.type === "narration" ? "[narration]" :
                               d.type === "sfx" ? "{SFX}" : "";
              
              // Character name
              pdf.setFont("helvetica", "bold");
              const charName = d.character || "Unknown";
              pdf.text(`${charName}:`, margin + 5, yPosition);
              
              // Dialogue text
              pdf.setFont("helvetica", "normal");
              const dialLines = pdf.splitTextToSize(`"${d.text}" ${typeLabel}`, contentWidth - 10);
              pdf.text(dialLines, margin + 5, yPosition + 4);
              yPosition += dialLines.length * 4 + 6;
            });
          }

          yPosition += 5;
        });
      }
    });

    // Generate PDF buffer
    const pdfBuffer = Buffer.from(pdf.output("arraybuffer"));

    // Calculate size
    const sizeKB = Math.round(pdfBuffer.length / 1024);
    const sizeDisplay = sizeKB > 1024 ? `${(sizeKB / 1024).toFixed(1)} MB` : `${sizeKB} KB`;

    // Return the PDF as downloadable response
    return new NextResponse(pdfBuffer, {
      status: 200,
      headers: {
        "Content-Type": "application/pdf",
        "Content-Disposition": `attachment; filename="${title.replace(/\s+/g, "-").toLowerCase()}.pdf"`,
        "Content-Length": pdfBuffer.length.toString(),
      },
    });

  } catch (error: any) {
    console.error("PDF export error:", error);
    return NextResponse.json(
      { success: false, error: error.message || "Export failed." },
      { status: 500 }
    );
  }
}
