import { NextRequest, NextResponse } from "next/server";
import { getProject } from "@/lib/db";
import * as archiver from "archiver";

/**
 * POST /api/export/cbz
 *
 * Exports a comic project as CBZ (Comic Book ZIP) format
 * CBZ is a ZIP file containing numbered page images
 */
export async function POST(request: NextRequest) {
  try {
    const body = await request.json();

    if (!body.sessionId) {
      return NextResponse.json(
        { success: false, error: "sessionId (projectId) is required." },
        { status: 400 }
      );
    }

    // Fetch project from database
    const project = await getProject(body.sessionId);
    
    if (!project) {
      return NextResponse.json(
        { success: false, error: "Project not found." },
        { status: 404 }
      );
    }

    // Check if project has approved pages
    const approvedPages = project.pages.filter(p => p.status === "approved");
    
    if (approvedPages.length === 0) {
      return NextResponse.json(
        { success: false, error: "No approved pages to export. Generate and approve pages first." },
        { status: 400 }
      );
    }

    const title = body.options?.title || project.title;

    // Create a PassThrough stream for the ZIP
    const { Readable } = await import("stream");
    const { promisify } = await import("util");
    const pipeline = promisify(require("stream").pipeline);

    // Create archiver instance
    const archive = archiver("zip", {
      zlib: { level: 9 }, // Best compression
    });

    // Create a readable stream from the archive
    const chunks: Buffer[] = [];
    
    archive.on("data", (chunk) => {
      chunks.push(chunk);
    });

    // Generate ComicInfo.xml metadata
    const comicInfo = `<?xml version="1.0" encoding="UTF-8"?>
<ComicInfo xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <Title>${title}</Title>
  <Series>${title}</Series>
  <Genre>${project.genre}</Genre>
  <Writer>Comicore AI</Writer>
  <Summary>${project.synopsis || ""}</Summary>
  <PageCount>${approvedPages.length}</PageCount>
  <LanguageISO>en</LanguageISO>
  <Manga>No</Manga>
  <Notes>Generated by Comicore AI - https://comicore.ai</Notes>
</ComicInfo>`;

    archive.append(Buffer.from(comicInfo), { name: "ComicInfo.xml" });

    // Generate placeholder images for each page
    // In a real implementation, these would be actual rendered comic pages
    const { createCanvas } = await import("canvas");
    
    approvedPages.forEach((page, index) => {
      const pageNum = String(index + 1).padStart(3, "0");
      
      // Create a canvas for the page (standard comic page ratio ~1.5:1)
      const width = 800;
      const height = 1200;
      const canvas = createCanvas(width, height);
      const ctx = canvas.getContext("2d");

      // Background
      ctx.fillStyle = "#1a1a1a";
      ctx.fillRect(0, 0, width, height);

      // Page border
      ctx.strokeStyle = "#333";
      ctx.lineWidth = 2;
      ctx.strokeRect(10, 10, width - 20, height - 20);

      // Title
      ctx.fillStyle = "#E8B931";
      ctx.font = "bold 24px Arial";
      ctx.textAlign = "center";
      ctx.fillText(page.title, width / 2, 60);

      // Page number
      ctx.font = "14px Arial";
      ctx.fillText(`Page ${index + 1}`, width / 2, height - 30);

      // Script summary
      ctx.fillStyle = "#999";
      ctx.font = "14px Arial";
      ctx.textAlign = "left";
      
      const maxWidth = width - 60;
      const lineHeight = 20;
      let y = 120;
      
      if (page.script) {
        const words = page.script.split(" ");
        let line = "";
        
        words.forEach((word) => {
          const testLine = line + word + " ";
          const metrics = ctx.measureText(testLine);
          
          if (metrics.width > maxWidth && line !== "") {
            ctx.fillText(line, 30, y);
            line = word + " ";
            y += lineHeight;
          } else {
            line = testLine;
          }
        });
        ctx.fillText(line, 30, y);
        y += lineHeight * 2;
      }

      // Panel descriptions
      if (page.panels && page.panels.length > 0) {
        ctx.fillStyle = "#666";
        ctx.font = "12px Arial";
        
        page.panels.forEach((panel, pIndex) => {
          if (y > height - 100) return; // Don't overflow
          
          ctx.fillStyle = "#E8B931";
          ctx.font = "bold 12px Arial";
          ctx.fillText(`Panel ${panel.panelNumber || pIndex + 1}`, 30, y);
          y += 18;
          
          ctx.fillStyle = "#888";
          ctx.font = "11px Arial";
          if (panel.description) {
            const descWords = panel.description.split(" ");
            let descLine = "";
            
            descWords.forEach((word) => {
              const testLine = descLine + word + " ";
              if (ctx.measureText(testLine).width > maxWidth) {
                ctx.fillText(descLine, 40, y);
                descLine = word + " ";
                y += 16;
              } else {
                descLine = testLine;
              }
            });
            ctx.fillText(descLine, 40, y);
            y += 20;
          }
          
          // Dialogue snippets
          if (panel.dialogue && panel.dialogue.length > 0) {
            ctx.fillStyle = "#aaa";
            ctx.font = "italic 10px Arial";
            panel.dialogue.slice(0, 2).forEach((d) => {
              if (y > height - 100) return;
              const dialogueText = `${d.character}: "${d.text.substring(0, 50)}${d.text.length > 50 ? "..." : ""}"`;
              ctx.fillText(dialogueText, 50, y);
              y += 14;
            });
            y += 10;
          }
        });
      }

      // Add to archive
      const buffer = canvas.toBuffer("image/png");
      archive.append(buffer, { name: `${pageNum}.png` });
    });

    // Finalize the archive
    await archive.finalize();

    // Wait for all chunks to be collected
    await new Promise((resolve) => {
      archive.on("end", resolve);
    });

    // Combine chunks into a single buffer
    const zipBuffer = Buffer.concat(chunks);

    // Calculate size
    const sizeMB = (zipBuffer.length / (1024 * 1024)).toFixed(2);

    // Return the CBZ as downloadable response
    return new NextResponse(zipBuffer, {
      status: 200,
      headers: {
        "Content-Type": "application/vnd.comicbook+zip",
        "Content-Disposition": `attachment; filename="${title.replace(/\s+/g, "-").toLowerCase()}.cbz"`,
        "Content-Length": zipBuffer.length.toString(),
      },
    });

  } catch (error: any) {
    console.error("CBZ export error:", error);
    return NextResponse.json(
      { success: false, error: error.message || "Export failed." },
      { status: 500 }
    );
  }
}
